services:
  - type: web
    name: predictai-backend
    env: python
    buildCommand: ""
    startCommand: python backend/main.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 5000

